### ISSUE TITLE
code 1012

### ISSUE THREAD

**Issue by lalala-code** [DePIN360/miner#1]
When my configuration is as follows, running the program will fail, and it will return error code 1012.
![image](https://github.com/user-attachments/assets/06b68373-694e-4d35-a4c3-a3ec135db02a)

**Comment by lalala-code** [comment]
like this
![image](https://github.com/user-attachments/assets/3a4ace4d-e1a0-4e97-a13b-87f8a9fd48d2)

**Comment by DePIN360** [comment]
This issue has been fixed in version v0.2.4, Please download and install the latest version again.
